- tabs/configuration.js
As the XBus support were merged into the cleanflight master, I also suggest that we add a setting for this in the configurator tab in the cleanflight-configurator tool. I added this with underscore, please let me know if this is ok or not. 
Edit: While reviewing the changes I realized that my editor (geany) had added a new-line (at the end of the file) in the source file. Please let me know if you do not want this.
Best regards
Stefan
> Added XBUS_MODE_B to serial rx configuration.

- tabs/servos.html
- tabs/servos.js
**!!!Limited testing has been done, so please check it out before considering merging!!!**
Added support for 16 channel receivers in servo control for tilt/gimbal. (4 standard channels + any number of active channels).
Number of Aux channels rendered = total channel count active on receiver - 4 ( allowing for 4 standard control channels )
i.e 8 Channels  = ch1, ch2, ch3, ch4, a1, a2, a3, a4
i.e 16 Channels  = ch1, ch2, ch3, ch4, a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12
Now you can utilise any of the additional channels to control the servos.  Initially done for servo tilt, but appears to be active for other servo modes as well, although these are untested.
I don't believe any firmware updates are required as its only a channel mapping.  Looking at the servo screens when armed, …
> Servo Channel Tab Configuration Update - supports 4-16 Channels for servo tilt mapping.

- js/msp.js
If my PR to add NMEA GPGSV info to cleanflight is accepted, depends on cleanflight#437 . In any case, the MSP request is sent and results processed without checking the GPS type so this comment wasn't accurate to begin with.
> Fix MSP_GPS_SV_INFO comment

- _locales/en/messages.json
- changelog.html
- js/data_storage.js
- js/gui.js
- js/libraries/jquery.flightindicators.js
- js/msp.js
- tabs/pid_tuning.css
- tabs/pid_tuning.html
- tabs/pid_tuning.js
Added TPA Breakpoint param change feature to PID tuning tab.
cleanflight/cleanflight-configurator#59
The above enhancement relies on the updated serial_msp.c:
cleanflight/cleanflight#601
Changed logging time stamp to include date stamp, for better tracking and comparison of screen shots.
cleanflight/cleanflight-configurator#103
Fixed artificial horizon Roll/Pitch views.
cleanflight/cleanflight-configurator#123
> Enhanced PID Tuning tab to set TPA Breakpoint

- tabs/pid_tuning.html
Previously r/p/y was allowed to be set to values higher than could be set using the CLI, and roll/pitch > 1.0 is meaningless (it causes the PID loop to actively destabilise flight).
> Update roll/pitch/yaw rate limits to match CF's limits

- _locales/en/messages.json
- js/data_storage.js
- js/msp.js
- tabs/receiver.css
- tabs/receiver.html
- tabs/receiver.js
Fixed. yaw expo is displayed correct and can be edited in receiver tab.
PR re-based on top of 0.63.2 d10023ec4b512395a07da9ac9f6d280f063a5fa6
Replaces #180
> Fixed: Access to Yaw expo in Receiver Tab

- _locales/en/messages.json
- js/msp.js
- manifest.json
- tabs/receiver.css
- tabs/receiver.html
- tabs/receiver.js
- tabs/receiver_msp.css
- tabs/receiver_msp.html
- tabs/receiver_msp.js
When the `RX_MSP` feature is enabled, this adds a "control sticks" button to the receiver tab. It pops up a dialog which has two control sticks and 4 aux sliders, which are transmitted to Cleanflight by MSP:
This feature is intended to allow developers to arm and debug Cleanflight without needing to attach a receiver or transmitter. (Because I'm currently on holiday without either of those!)
The "control sticks" button is not shown if `RX_MSP` isn't enabled, so regular users will probably never see it. 
I think my neighbours will appreciate not hearing "Telemetry lost! Telemetry recovered!" from my transmitter all evening.
> Add control sticks for MSP Rx, suitable for debugging CF without a Tx

- tabs/sensors.js
This fixes the bug (#240) which causes the Sensors tab to freeze upon initialisation on Chrome 46.
> Sensor tab: Fix freeze on tab open on Chome 46

- js/msp.js
Fixes #226 by properly rounding floating point values as they are scaled and stored as integers in msp.js's `crunch()`.
> Fix rounding of floating point values in crunch() (rc_rate, pids, etc)

- js/backup_restore.js
- js/msp.js
- tabs/failsafe.js
@hydra This is the change you mentioned on IRC the other day:
~~~
[22:04] <hydra_> ProDrone: if we ever support more than 18 channels we will have a problem with this:
[22:04] <hydra_> #define MSP_SET_RXFAIL_CONFIG           78 //in message          Sets RXFAIL settings
[22:04] <hydra_> #define INBUF_SIZE 64
[22:05] <hydra_> 18 * 3 = 54
[22:05] <hydra_> just so you're aware.
[22:05] <hydra_> a different approach is taken for things like the LED_STRIP configuration, etc.
[22:06] <hydra_> an index is supplied with the data. and one message is set for each index that needs to be sent.
[22:07] <hydra_> in an alternative world the FC would then be sent up to 18 rxfail messages, each with an index and 3 extra bytes payload
[22:07] <hydra_> no worries.  might be worth doing this now before the …
> MSP_SET_RXFAIL_CONFIG changed to allow more future RX channels

- tabs/cli.js
This fixes the undefined reference error and allows the configurator to automatically switch to the main tab after exiting the CLI.
> CLI: Fix error after exit command

- tabs/motors.css
- tabs/motors.html
- tabs/motors.js
Many people balance their props but only few balance also their motors. However, I found in my quadcopter that balancing the motors themselves increased the stability quite a bit.
If you look around (e.g. on youtube) you will find people gluing their smartphones to their copters to measure the vibrations. The smartphone application gives you the RMS of the vibrations, so you directly have a number for the *amount of vibrations* in your system. So if you do certain thing to balance the motor you can see if you are doing the right thing.
My pull request implements the computation and display of the vibration RMS in the Motors tab of the Cleanflight Configurator.
Note: The time scale of the RMS computation can be set by changing the refresh rate of the graph.
**This is an important feature …
> Add vibrations RMS to Motors tab

- main.css
- tabs/setup.js
If no mag sensor is present the button is disabled but it was styled like all other active buttons.
This PR adds a new deactivated style to that button
> Mag calibration button fix in the setup tab

- tabs/configuration.html
The FC rejects all values >1599 and <1401.
> Mid Throttle min/max value correction

- js/backup_restore.js
- js/gui.js
* In order to sort backup files (by backup created time, not file created/modified date) it's compulsory to use ISO date formatting (`YYYY-MM-DD`). The new filename pattern with these changes will be: `cleanflight_backup_YYYY-MM-DDTHH-MM` (e.g. `cleanflight_backup_2016-03-06T17-52`).
* Further, this PR simplifies the timestamp generation in the log section and gives the user a localized time format (e.g. '5:52:24 PM' for English users, '17:52:24' for me, etc.)
> ISO date for backup filename, localized timestamps in logs

- _locales/en/messages.json
- js/msp.js
- tabs/ports.js
Companion to https://github.com/cleanflight/cleanflight/pull/2415 adds a new telemetry mode in the ports tab.
> Add iBus telemetry option in ports tab

- _locales/en/messages.json
I'm not sure what references to BetaFlight must be let. But I think this two must be removed (or at least corrected in some way).
> Corrections to some BetaFlight references

- js/backup_restore.js
- main.js
- tabs/logging.js
- tabs/onboard_logging.js
This PR solves https://github.com/cleanflight/cleanflight-configurator/issues/453
The extension for saved files is `BFL` (BetaFlight Log). They must be `CFL` (CleanFlight Log) or use a unique file extension `BBL`  (BlackBox Log).
This PR uses `BBL` as extension, as suggested in the issue by @mikeller, but I can change it if to `CFL` if finally this is the preferred way (in this way, by the extension we can know what software has recorded the log).
@hydra what do you think?
> Change the extension of blackbox saved files

- README.md
Connecting Cleanflight Configurator to my SPRacingF3Evo did not work out-of the box, and I spent hours getting it work.
There is too little information of the web what actual kernel driver is used, how the device manifests itself etc.
Let's add all the technical information to README.md to save others from doing the research instead.
Perhaps the information is too technical/long? OTOH I did not find a better place to put this. There is 
https://github.com/cleanflight/cleanflight/blob/master/docs/USB%20Flashing.md - but that is related to flashing, and first-time users will likely just try to connect the configurator first.
> RADME.md: rework connection notes for Linux users

- tabs/osd.js
Remove space from throttle and added K to speed, to adjust to the way the real OSD shows this values.
> Update OSD preview for Throttle and GPS speed to adjust to reality

- _locales/es/messages.json
Complete translation of the messages file into spanish. 
There was an abandoned PR trying to do this: https://github.com/cleanflight/cleanflight-configurator/pull/446
Some things:
- Everybody can collaborate in the translation, don't need coding knowledge. Only go to this URL: http://cleanflight.oneskyapp.com/  I can add all the languages that the community want to translate.
- I've translated all words (but roll, pitch and yaw, I think this three words are better understood in english). The community will tell if this is correct or is better to translate all or let some other words untranslated.
- Some strings were not in the messages file, so they're not translated. This can be solved progressively in futures PR. 
- I think there's a need for a PR to let the user select the language in …
> Translate the GUI into spanish language

- js/Features.js
Resolves an issue where GUI fails to load (falling back to CLI) caused by syntax error because of the comma after the last item in the array.
> remove trailing "," which causes error in GUI
