cleanflight/cleanflight-configurator

tabs/firmware_flasher.js
The displayed date and time is now correct.
(first pull request I made ever... hope I did everything correctly.)
=> Fixed the displayed firmware-date in the firmware flasher.

README.md
Cleaned up some spelling and capitalization in README.
=> Cleaned up some spelling and capitalization.

_locales/en/messages.json
Update messages adjustments PID to more accurate versions.
=> Update messages adjustments

tabs/led_strip.css, tabs/led_strip.html
Added a quadrant grid in the bg and improved highlighting
=> Led grid tweaks

main.css
=> Fix tabs disappear on Chrome 41 Beta

tabs/configuration.css, tabs/configuration.js
Tried to create a pull-request based on the development branch...hopefully this was correct. Please let me know if I should do this in some other way...still very new to all these things...but hopefully I am learning. :)
=> Added new XBUS_MODE_B_RJ01 (for Align DMSS RJ01 receiver) 

js/data_storage.js, js/msp.js, tabs/sensors.html, tabs/sensors.js
Implementation of #379, configurator part.
@hydra Sorry about that, still learning git. I hope that this one is good now :-)
=> Add sonar to sensors

js/msp.js
Interpret MSP_ANALOG.amperage value as signed
=> Allow negative current draw

js/serial_backend.js, main.css, main.html
After connecting to a CFL firmware a link to the corresponding GitHub branch / docs directory will be shown in the upper right corner next to the options button.
=> Show a link to the documentation

main.css, tabs/cli.css, tabs/cli.html
Checkbox was previously unclickable if watermark was covering it.
=> Stop watermark from covering up "motor test" checkbox

tabs/pid_tuning.html, tabs/pid_tuning.js
Fixes PID/RC values being overwritten when changing to a PID controller with different default values / FC "memory-slot".
=> made pid or pidController change exclusive, always refresh from FC after

js/msp.js
ArrayBuffer does NOT have length but byteLength parameter.
=> fix for undefined function

js/port_handler.js, js/serial_backend.js, main.css, main.html
On some systems Bluetooth serial ports are not enumerated by the chrome API. This PR adds an manual serial port configuration option to the DropDown list.
=> Manual comport selection

tabs/cli.css, tabs/cli.html
=> Preserve consecutive whitespace characters in CLI output

tabs/dataflash.js
This fixes the situation where if the dataflash already had some data on it before you entered the dataflash tab, then you began recording a new log, then you finished recording, and (without leaving the tab) you clicked save to save it to disk, it would only save the old flight and not the new data.
=> Update used flash size before dataflash save begins so that new data is not missed

js/msp.js
Detect, register, skip and log the unsupported message error from the FC
=> Handle unsupported MSP messages

_locales/en/messages.json, tabs/setup.css, tabs/setup.html, tabs/setup.js
Added rolling pitch to the set up tab to make it easier to orientate flight controller if it's slightly skewed.
=> Added Roll & Pitch to Setup Tab

js/boards.js, tabs/configuration.js, tabs/ports.js
Please let me know if there has any problem.
=> COLIBRI RACE Support pull request

tabs/servos.js
As the issue #170, but in the correct branch
=> Increase range because some analog servo

tabs/firmware_flasher.js
Fix the regular expression can not show correctly if the name having more then one "_".
=> - Fix the regular expression problem

tabs/firmware_flasher.js
Reverts cleanflight/cleanflight-configurator#260
=> Revert 5ca82390922872f6eb60f2e9205717c3cb78d065

support/svg_model_motors.rb
Update motor diagrams to new colour theme
=> update motor diagrams to new colour theme

tabs/receiver.js
it now matches the value range in the firmware
tested with just the naze32 board
=> rssi_channel range is from 1-12 in firmware

js/gui.js, tabs/firmware_flasher.js
Fix for issue #274 
This may need additional testing. I just needed to wrap it up for now.
=> Fix for issue #274 (checkboxes on firmware flasher)

tabs/servos.js
angleAtMin is always positive, so we have to manage its inverted-user friendly rappresentation
=> Fix servo range

_locales/en/messages.json
Simple fix, will look for something more useful next.
=> Fixes issue #283

tabs/landing.html
=> Fix sponsor URL on welcome tab.

tabs/failsafe.css, tabs/failsafe.html
Styling removed from HTML to CSS including a bit of CSS cleanup.
=> Failsafe TAB style to css

_locales/en/messages.json, js/gui.js, tabs/failsafe.css, tabs/failsafe.html, tabs/failsafe.js
=> jBox Tooltip implementation using i18n_title, instead of populating jBox: Content - reduces DOM element counts

js/serial.js
This attempts to recover after a break condition (occurs during reboot on older firmware versions). Tested and confirmed to work on Windows 10.
=> Serial: Attempt recovery of break condition

tabs/configuration.html, tabs/motors.html, tabs/motors.js
Only tested against 'allowTestMode' and Not 'feature3DSupported'
@hydra - please check to see if this PR addresses  #297 and #233
Many thanks
=> Motors test mode switch and dynamically enabling/disabling sliders

_locales/en/messages.json, js/protocols/stm32usbdfu.js
Fixes the remaining item in #250. Can now support chips other than F303.
=> USB-DFU: Detect flash page size from USB descriptor

_locales/en/messages.json, tabs/configuration.html, tabs/configuration.js
Additional pull request to #310 
To make #311 update every 250ms
Add current meter readout  also to configuration tab (This bit is untested as I don't have a current meter)
=> Add Current and Voltage readout on configuration tab

main.css
Small CSS fixes for https://github.com/cleanflight/cleanflight-configurator/pull/372
=> cleanup for #74

tabs/setup.css, tabs/setup.html
=> Removing calibration status animation from setup tab

js/msp.js, tabs/led_strip.css, tabs/led_strip.html, tabs/led_strip.js
Implement initial support for new LED commands implemented in CF PR
2101.
=> Support LED cmds GPS, RSSI & Blink in configurator

js/msp.js, tabs/configuration.html, tabs/configuration.js
Allow declination to be set exactly in degrees,minutes (therefore uses
exactly the same value as in CLI instead of rounding it)
Requires cleaflight patch available in this PR: https://github.com/cleanflight/cleanflight/pull/2055
=> Issue #153: finer mag_declination in GUI

tabs/failsafe.html
=> Issue #363: max failsafe_delay should be 200

_locales/en/messages.json, js/msp.js, tabs/ports.js
Support for https://github.com/cleanflight/cleanflight/pull/806
Supersedes https://github.com/cleanflight/cleanflight-configurator/pull/161.
=> Support for MAVLink telemetry

js/serial_backend.js
=> Fix: Gyro icon shown as not active if acc sensor is deactivated in the CLI

_locales/en/messages.json, js/backup_restore.js, js/fc.js, js/msp.js, manifest.json, tabs/led_strip.css, tabs/led_strip.html, tabs/led_strip.js
For discussion, this is a first shot at implementing LED Strip commands in GUI : 
- Color setup (HSV sliders) of the 16 colors in the palette (cli command color)
- Mode Colors and Special Colors setup: click on one of the buttons, then on a color in the palette (requires https://github.com/cleanflight/cleanflight/pull/2173)
Backup files also now include the LED color and mode color data.
=> LED Strip GUI: color, mode color setup

_locales/en/messages.json, tabs/configuration.html
Asked for in: https://github.com/cleanflight/cleanflight-configurator/issues/391
=> Serial RX help tooltip

js/msp.js, tabs/pid_tuning.html, tabs/pid_tuning.js
PID values are scaled between 0 and 255 by increments of 1.
Also removed un-used Pos I value from PID table.
Fixes https://github.com/cleanflight/cleanflight-configurator/issues/383
=> Apply scaling to PID values

js/msp.js, tabs/gps.js
Clear GPS_DATA arrays used by MSP_GPS_SV_INFO before filling them.
Fixes https://github.com/cleanflight/cleanflight-configurator/issues/78
=> GPS - Clear Signal Strength Data

_locales/en/messages.json, tabs/firmware_flasher.html, tabs/firmware_flasher.js
=> Add target and firmware version selects to firmware flasher tab

js/msp.js, tabs/led_strip.css, tabs/led_strip.html, tabs/led_strip.js
Handle new MSP LED config format (not yet merged)
New function: Battery
RSSI is now a function (similar to battery, with blinking on low)
Blink is now an overlay
New overlays: Larson scanner, blink on landing
New overlay mixing possibilities
Requires the CF build resulting from https://github.com/cleanflight/cleanflight/pull/2160
Compatible with previous versions
NOT TO BE MERGED until https://github.com/cleanflight/cleanflight/pull/2160 is finalized.
=> LEDstrip: Battery, Larson scanner, Blink on landing

tabs/configuration.js
Added JETI EX BUS Protocol under SerialRX Provider List on Configuration
Support in BetaFlight (2.4.0) borisbstyle/betaflight#168
Upcoming Support in Cleanflight Pull Request
cleanflight/cleanflight#1709
Issue #339
=> Added JETI EX BUS Protocol under SerialRX Provider List on Configuration

tabs/led_strip.js
=> Fix LED strip mode colors on API 1.19

_locales/en/messages.json, tabs/transponder.css, tabs/transponder.html, tabs/transponder.js
Hi,
I did changes what you wanted.
reference to https://github.com/cleanflight/cleanflight-configurator/pull/445
=> Support for next lap timer

main.css
save button / toolbar now fixed on bottom
=> fixed save button in power-tab

tabs/power.html
brings the battery box on top ... imho more logical order ;)
=> rearrange power-tab

tabs/power.html
removed empty voltage and amperage box ... same bug fixed in bf configurator ![dffd5c9c-30ce-11e7-97ca-1af541bbd9fb](https://cloud.githubusercontent.com/assets/20139767/25718712/6901f1aa-3107-11e7-81de-c8ecfcf8222c.jpg)
=> fixed update request

_locales/en/messages.json, js/msp/MSPHelper.js, tabs/auxiliary.js, tabs/ports.js
=> Add runcam split support

tabs/transponder.js
Fix setting of transponder type to 'None'.
=> From Betaflight: Fix setting of transponder type to 'None'.

src/tabs/landing.html
Many thanks to the support from the sponsors, without which Cleanflight wouldn't be where it is today.
=> Remove out-dated Sponsors panel.

src/js/tabs/vtx.js
=> Fix broken VTX tab when vtxtables is not available.
